<a href="https://colab.research.google.com/github/RavinderSinghPB/ML-AND-CV/blob/master/Untitled2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!sudo apt install tesseract-ocr
!pip install pytesseract

In [2]:
import pytesseract
import shutil
import os
import random
try:
 from PIL import Image
except ImportError:
 import Image

In [ ]:
from google.colab import files
uploaded = files.upload()

In [10]:
for i in range(1,10):
    s='Grade Card-0'+str(i)+'.jpg'
    extractedInformation = pytesseract.image_to_string(Image.open(s))
    print(extractedInformation)

Date of Birth 7 Nov
Town/city Erode

Mathematics 68

aes ey |

Chemistry 78
TOTAL Imi’











Name Harish ©

Gender YJ



Date of Birth 3 Ju ne
Town/City Salem

Mathematics 62

saat (es A5

Chemistry oy

ONT NE ue} 33











Date of Birth 4 Ja n
Town/City C al enna

Mathematics 5/

Physics wy!

Chemistry T/
TOTAL | 88











Name Rida ©

Gender F

Date of Birth 5 May
Town/ciy Chennal

Mathematics

aaa

Chemistry

TOTAL uae:











Nee tia] ee 4)

Gender F

Date of Birth 17 Nov
Town/city Madural

Mathematics 87

ANAT eS 64

Chemistry 89
TOTAL J2AO0











Name AkShaya ©

Gender F

Date of Birth 8 Feb
Town/ciy Chennal

Mathematics T1

Physics oW

Chemistry rs yA
Oye ND 24]











Name Sameer

Ct TaTolTam \V/
Date of Birth 23 Mar
Town/city Ambur

Mathematics

aes

Chemistry

TOTAL











SWNT 7

Gender YJ



Date of Birth 15 Mar
Town/city Yellore

Mathematics 84

aes oW

Chemistry VAs)
TOTAL Vas W











Name Surya ©

(et TaTe(Tam \V/

Date of Birth J8 Feb
Town/ciy Bengaluru

Mathematics T4

Physics ey |

Chemistry 51

TOTAL 189